### ISSUE TITLE
Bundan olmaz gidin Pythonun pipi kullanın

### ISSUE THREAD

**Issue by ilker610** [themispkg/themis#1]
Pipi alır bunu

**Comment by lazypwny751** [comment]
kardes, piton bash'ımı yesin.

**Comment by ilker610** [comment]
İki köylü bir araya gelir biri diğerine derki benim hanım ipimi istiyor. diğeri der ki ipim ne adam der ki pipim 

@everyone

**Comment by lazypwny751** [comment]
bos yabma cay yab
